services:
  - type: web
    name: paper-metrics-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: HF_HUB_ENABLE_HF_TRANSFER
        value: "1"